// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Safe env access for both Next.js and Vite builds (avoids `process` in browser)
const nextEnv =
  typeof process !== 'undefined' && process.env ? process.env : {};

const SUPABASE_URL =
  nextEnv.NEXT_PUBLIC_SUPABASE_URL ||
  (typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env.VITE_SUPABASE_URL : '') ||
  '';

const SUPABASE_PUBLISHABLE_KEY =
  nextEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  (typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY : '') ||
  '';

// Safe storage for SSR
const isBrowser = typeof window !== 'undefined';
const storage = isBrowser ? window.localStorage : undefined;

// Only create client if we have valid credentials
export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: storage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createClient<Database>('https://placeholder.supabase.co', 'placeholder-key', {
      auth: {
        storage: storage,
        persistSession: false,
        autoRefreshToken: false,
      }
    });
